### ISSUE TITLE
Upcoming issues for next version `check_overlinking_impl`

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/python-chromedriver-binary-feedstock#19]
Issue:

In fixing #18, saw this on linux:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=37959
```
Packaging python-chromedriver-binary
INFO:conda_build.build:Packaging python-chromedriver-binary
INFO:conda_build.build:Packaging python-chromedriver-binary-74.0.3729.6.0-py27_0
Packaging python-chromedriver-binary-74.0.3729.6.0-py27_0
compiling .pyc files...
number of files: 13
ERROR :: get_rpaths_raw()=[] and patchelf= disagree for /home/conda/feedstock_root/build_artifacts/python-chromedriver-binary_1558994581536/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python2.7/site-packages/chromedriver_binary/chromedriver :: 
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2299, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1596, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 958, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 823, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 1070, in post_build
    check_overlinking(m, files)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 1009, in check_overlinking
    m.config.channel_urls)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 930, in check_overlinking_impl
    needed = needed_dsos_for_file[f]
KeyError: 'lib/python2.7/site-packages/chromedriver_binary/chromedriver'
```

We'll probably have to do some fiddling to make it all work with some of the newer safety measures.

**Comment by lohedges** [comment]
I believe the error is because you are simply downloading a pre-compiled binary, which hasn't been compiled on the Conda Forge host platform using its own compilers, i.e. by adding the following to the build section of your recipe:

```sh
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
```

This change seems to have been introduced in `conda-build` 3.18, although I can't see it documented anywhere. I guess this means that all Conda Forge packages that use pre-compiled binary files re now broken.

**Comment by lohedges** [comment]
Downloading your latest Linux recipe from [here](https://anaconda.org/conda-forge/python-chromedriver-binary/files):

__conda-build 3.18__ (build fails with `KeyError`)

```
ERROR :: get_rpaths_raw()=[] and patchelf= disagree for /home/lester/.conda/envs/test/conda-bld/python-chromedriver-binary_1560511886255/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/chromedriver_binary/chromedriver ::
/usr/bin/nm: dynamic_annotations.o: no symbols
Traceback (most recent call last):
  File "/home/lester/.conda/envs/test/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/lester/.conda/envs/test/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/home/lester/.conda/envs/test/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/home/lester/.conda/envs/test/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/lester/.conda/envs/test/lib/python3.7/site-packages/conda_build/build.py", line 2299, in build_tree
    notest=notest,
  File "/home/lester/.conda/envs/test/lib/python3.7/site-packages/conda_build/build.py", line 1596, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/home/lester/.conda/envs/test/lib/python3.7/site-packages/conda_build/build.py", line 958, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/home/lester/.conda/envs/test/lib/python3.7/site-packages/conda_build/build.py", line 823, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/home/lester/.conda/envs/test/lib/python3.7/site-packages/conda_build/post.py", line 1070, in post_build
    check_overlinking(m, files)
  File "/home/lester/.conda/envs/test/lib/python3.7/site-packages/conda_build/post.py", line 1009, in check_overlinking
    m.config.channel_urls)
  File "/home/lester/.conda/envs/test/lib/python3.7/site-packages/conda_build/post.py", line 930, in check_overlinking_impl
    needed = needed_dsos_for_file[f]
```

__conda-build 3.17__ (warnings, but package build completes)

```
patchelf: file: /home/lester/.conda/envs/test/conda-bld/python-chromedriver-binary_1560511989853/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/chromedriver_binary/chromedriver
    setting rpath to: $ORIGIN/../../..
WARNING: Disagreement in get_linkages(filename=/home/lester/.conda/envs/test/conda-bld/python-chromedriver-binary_1560511989853/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/chromedriver_binary/chromedriver, resolve_filenames=True, recurse=False, sysroot=, envroot=/home/lester/.conda/envs/test/conda-bld/python-chromedriver-binary_1560511989853/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho, arch=native):
 lief: {'$RPATH/libnss3.so', '$RPATH/libX11.so.6', '$RPATH/librt.so.1', '$RPATH/libnssutil3.so', '$RPATH/libnspr4.so', '$RPATH/libm.so.6', '$RPATH/libglib-2.0.so.0', '$RPATH/libdl.so.2', '/home/lester/.conda/envs/test/conda-bld/python-chromedriver-binary_1560511989853/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/chromedriver_binary/../../../libgcc_s.so.1', '$RPATH/libc.so.6', '$RPATH/libpthread.so.0', '$RPATH/ld-linux-x86-64.so.2'}
pyldd: {'/lib/libm.so.6', '/lib/libnssutil3.so', '/lib/libc.so.6', '/lib/librt.so.1', '/lib/libglib-2.0.so.0', '/lib/libnss3.so', '/lib/libdl.so.2', '/lib/libnspr4.so', '/lib/libpthread.so.0', '/home/lester/.conda/envs/test/conda-bld/python-chromedriver-binary_1560511989853/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/chromedriver_binary/../../../libgcc_s.so.1', '/lib/libX11.so.6', '/lib/ld-linux-x86-64.so.2'}
  (using lief)
nm: dynamic_annotations.o: no symbols
WARNING (python-chromedriver-binary,lib/python3.7/site-packages/chromedriver_binary/chromedriver): did not find - or even know where to look for: $RPATH/libnss3.so
WARNING (python-chromedriver-binary,lib/python3.7/site-packages/chromedriver_binary/chromedriver): did not find - or even know where to look for: $RPATH/libX11.so.6
WARNING (python-chromedriver-binary,lib/python3.7/site-packages/chromedriver_binary/chromedriver): did not find - or even know where to look for: $RPATH/librt.so.1
WARNING (python-chromedriver-binary,lib/python3.7/site-packages/chromedriver_binary/chromedriver): did not find - or even know where to look for: $RPATH/libnssutil3.so
WARNING (python-chromedriver-binary,lib/python3.7/site-packages/chromedriver_binary/chromedriver): did not find - or even know where to look for: $RPATH/libnspr4.so
WARNING (python-chromedriver-binary,lib/python3.7/site-packages/chromedriver_binary/chromedriver): did not find - or even know where to look for: $RPATH/libm.so.6
WARNING (python-chromedriver-binary,lib/python3.7/site-packages/chromedriver_binary/chromedriver): did not find - or even know where to look for: $RPATH/libglib-2.0.so.0
WARNING (python-chromedriver-binary,lib/python3.7/site-packages/chromedriver_binary/chromedriver): did not find - or even know where to look for: $RPATH/libdl.so.2
WARNING (python-chromedriver-binary,lib/python3.7/site-packages/chromedriver_binary/chromedriver): Needed DSO lib/libgcc_s.so.1 found in ['libgcc-ng']
WARNING (python-chromedriver-binary,lib/python3.7/site-packages/chromedriver_binary/chromedriver): .. but ['libgcc-ng'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
WARNING (python-chromedriver-binary,lib/python3.7/site-packages/chromedriver_binary/chromedriver): did not find - or even know where to look for: $RPATH/libc.so.6
WARNING (python-chromedriver-binary,lib/python3.7/site-packages/chromedriver_binary/chromedriver): did not find - or even know where to look for: $RPATH/libpthread.so.0
WARNING (python-chromedriver-binary,lib/python3.7/site-packages/chromedriver_binary/chromedriver): did not find - or even know where to look for: $RPATH/ld-linux-x86-64.so.2
WARNING (python-chromedriver-binary): dso library package conda-forge::python-3.7.3-h5b0a415_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
Fixing permissions
Packaged license file.
Detected hard-coded path in text file bin/chromedriver-path
Compressing to /tmp/tmpjyzp1rnc/python-chromedriver-binary-75.0.3770.8.0-py37_0.tar.bz2
```

**Comment by bollwyvl** [comment]
This appears to have been resolved in the most recent release with conda/conda-build.
